CREATE TABLE IF NOT EXISTS filters(id INTEGER PRIMARY KEY, textt VARCHAR(300), maxd DATE, mind DATE, typ VARCHAR(300), bywho VARCHAR(300), lon INTEGER, lat INTEGER, area INTEGER)
CREATE TABLE IF NOT EXISTS wildlife(id INTEGER PRIMARY KEY, userid INTEGER, typ TEXT, species TEXT, notes TEXT, lon FLOAT, lat FLOAT, datee TEXT, photo TEXT)
